// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitApi.Models;

#nullable disable

namespace RecruitApi.Migrations
{
  [DbContext(typeof(SystemDbContext))]
  [Migration("20230629065326_InitialCreate")]
  partial class InitialCreate
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "7.0.0")
          .HasAnnotation("Relational:MaxIdentifierLength", 128);

      SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

      modelBuilder.Entity("RecruitApi.Models.User", b =>
          {
            b.Property<long>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("bigint");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

            b.Property<bool>("IsActive")
                      .HasColumnType("bit");

            b.Property<string>("Name")
                      .HasColumnType("nvarchar(max)");

            b.HasKey("Id");

            b.ToTable("Users", (string)null);
          });
#pragma warning restore 612, 618
    }
  }
}
